### ISSUE TITLE
Email Opens / Click Tracking

### ISSUE THREAD

**Issue by MuratKaragozgil** [postalhq/postal#1006]
Hi,

How to pass email open events to external system ? I'm already using webhooks but it's not calling external system when an email opened. But link click events are working.

And also i want to ask, i clicked the link in the email only once, but webhook calling to external system 3 times. What is the problem ?

Screenshots are below;

<img width="594" alt="Screen Shot 2020-02-28 at 08 20 39" src="https://user-images.githubusercontent.com/8644827/75512678-3ba08a00-5a03-11ea-8568-86c66818b643.png">

<img width="287" alt="Screen Shot 2020-02-28 at 08 20 30" src="https://user-images.githubusercontent.com/8644827/75512681-3e02e400-5a03-11ea-91fe-1624c7007014.png">

**Comment by willpower232** [comment]
Message open tracking is done via a small image being loaded but these days its very easy for an email client to not load the images by default.

Its possible that whatever email system you are using followed the links as well to be sure they were genuine and didn't link to a bad website so that would account for the extra clicks.

You could try different email clients or addresses, i.e. outlook, hotmail, gmail, to see what behaviours you get.

Is your problem that you aren't getting all the events triggered or that you're having a problem sending the ones you do get to httpbin?

**Comment by MuratKaragozgil** [comment]
Hi, Okay multi event trigger is not problem, but email opens is not triggered httpbin. I want to send send event to httpbin when an email opened. How can i do it ?

**Comment by willpower232** [comment]
Have you tried a sending to a different email client or address to see if the tracking works then?

**Comment by MuratKaragozgil** [comment]
Yes i tried but i actually want to ask you how to send email opens via webhook. Im looking the webhook page, what i want is not listed. (Email Open Event). 

<img width="633" alt="Screen Shot 2020-02-29 at 14 21 40" src="https://user-images.githubusercontent.com/8644827/75606551-feb9bd80-5afe-11ea-8791-3fe22c74a4cc.png">

**Comment by willpower232** [comment]
Ah yes, Postal calls that event `MessageLoaded`

**Comment by zeba121** [comment]
Hello @MuratKaragozgil 

can you help me how can I configure open and click tracking?

Please help me.

Thank You
