### ISSUE TITLE
Easy to have tracking and main web interface on the same IP with nginx proxy_pass

### ISSUE THREAD

**Issue by nhadsall** [postalhq/postal#1009]
In case it helps anyone else, I simply have this in my postal.yml
```
fast_server:
  enabled: true
  bind_address: 127.0.0.1
  port: 8080
  ssl_port: 11443
```

and this in my nginx configuration
```
server {
    server_name tracking.example.com;

    listen [::]:443 ssl ipv6only=on; 
    listen 443 ssl; 
    ssl_certificate /etc/letsencrypt/live/tracking.example.com/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/tracking.example.com/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot

    location / {
        proxy_set_header X-Real-IP  $remote_addr;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto https;
        proxy_pass http://127.0.0.1:8080;
   }
}
```

And since the server settings for the main interface are  `server_name example.com;` No one will accidentally see the wrong site.

That way you don't even have to worry about fast_server having an ssl cert

**Comment by willpower232** [comment]
Thanks for the notes.

See also https://github.com/postalhq/postal/issues/664#issuecomment-424267406

**Comment by layen67** [comment]
proxy_pass http://127.0.0.1:8080;

**Comment by nhadsall** [comment]
Thanks @layen67, you are right. I fixed the typo in the config here. 

One thing @willpower232 did point out is that you have to add the server config an do an initial cerbot setup for each new tracking domain. 

Personally it seems like something Postal could do easily to manage these. I'm curious why they went the route they did. It seems this is a much easier setup so people don't need to waste an IP.

**Comment by willpower232** [comment]
Postal is set up to be essentially a white-label solution so the management of the domains can be fully handled by whoever is in charge of the UI rather than needing to modify the underlying server configuration.

I think the code is a combination of traditional ruby on rails and some more directly connected ruby so handling ALL the HTTP requests internally would be complicated and/or annoying so is easier handled by separate IPs or a proxy such as nginx.

Not every operator of Postal has a client base who wants to manage these things directly so hosting it differently according to your skillset and requirements means you get a little overkill I guess.

**Comment by Igcorreia** [comment]
@nhadsall 🙏🙏🙏 to notes here for other users. Make sure your PORT is open. And I have change one line of code, the one forcing ipv6

**Comment by Igcorreia** [comment]
After configuration I have to set up CERTBOT manually.

**Comment by adamcooke** [comment]
This is related to fast server which will be going as per #1427
