### ISSUE TITLE
Email Relay

### ISSUE THREAD

**Issue by WizardKid** [postalhq/postal#1018]
My main reason I’ve installed Postal is to remove my dependency from Sendgrid and handle emails on my own. I would like to configure my servers to send/receive emails through postal through use of api (similar to Sendgrid). So far: the test emails not sending (softfail) but can receive from external source. The logs showing postal is trying to send emails using port 25 even though in postal it is set to 2525. Not sure what other steps I need to take - is there an extensive documentation available and is there a future for postal or am I able to extend this with my own functionalities?

**Comment by willpower232** [comment]
Are you able to see the reason for the fail in the UI? Can you send a screenshot?

Port 25 is part of the standard so that is how Postal will connect to other email servers. The port 2525 setting is for how you wish to connect to your own Postal server from your other software.

The documentation is all here and in the wiki currently.

As it is MIT licenced open source, you are able to make your own changes to the source code, if you wish and happen to know Ruby on Rails.
