### ISSUE TITLE
Don't change IP in SOFT FAIL 

### ISSUE THREAD

**Issue by masihfathi** [postalhq/postal#1044]
Hi , We know that when we got "SOFT FAIL" most of the time cause of IP limit or complaints and it can solve with change ip in next try. but postal send with same ip even if some ips available in IP Pools

**Comment by AndersonOuverney** [comment]
Hello, how are you?
I currently also use IP pools for sending, I have doubts about the turnover of delivery of new emails.

**Comment by willpower232** [comment]
As per https://github.com/postalhq/postal/blob/master/app/models/queued_message.rb

I'm not completely sure but it looks like the IP address from the pool is determined with the message is initially queued so retries would re use the same IP address.

Presumably you could modify that file so that the IP address was re allocated when retries occurred.

**Comment by masihfathi** [comment]
hi thank you for your help. i check the class and add a call to allocate_ip_address method after this line https://github.com/postalhq/postal/blob/master/app/models/queued_message.rb#L87
in this way `self.class.allocate_ip_address` but it did not work, i'm not really familiar with ruby. would mind help me
