### ISSUE TITLE
remove / uninstall postal and all dependencies

### ISSUE THREAD

**Issue by donjuanme** [postalhq/postal#1075]
hi

i need to remove / uninstall postal from a server as i am moving servers , is there a method or script i can use to make this as simple as the install process ?

**Comment by willpower232** [comment]
There is not, Postal works best if it is on its own server rather than alongside other things so most cleanups would just be cancelling the whole server.

If you have installed Postal alongside other things then a full uninstall script would likely cause problems for whatever else is on the server, particularly databases.

Apart from the files and however you start Postal on boot, all of Postal is in databases which should be easy to remove from MySQL if you need to keep it installed.

**Comment by KSATDesign** [comment]
i use ``rm -Rf /opt/postal /usr/bin/docker-compose /usr/bin/postal && docker rm -fv postal postal-rabbitmq postal-mariadb postal-caddy`` on centos doesnt remove dependancies like git curl jq although could simply 

``rm -Rf /opt/postal /usr/bin/docker-compose /usr/bin/postal && docker rm -fv postal postal-rabbitmq postal-mariadb postal-caddy && apt remove git curl jq etc`` for debian

or 

``rm -Rf /opt/postal /usr/bin/docker-compose /usr/bin/postal && docker rm -fv postal postal-rabbitmq postal-mariadb postal-caddy && yum -y remove git curl jq etc`` for centos
