### ISSUE TITLE
Build a new mail server error !!!

### ISSUE THREAD

**Issue by masymars** [postalhq/postal#1089]
when i completed installation of postal in my server when i get to create a mail server it's keep there loading and nothing happens.

**Comment by willpower232** [comment]
You will need to look in the log files to see what is happening.

**Comment by JudgeAdil** [comment]
hello, i have the same problem, installation went good on ubuntu 18 server hosted at Digitalocean, but after creating organization, i can't build  a mail server, the green button just keeps showing that it's loading, but nothing happens. Thanks for your time

**Comment by wasims1** [comment]
for anyone coming here for this issue, here's the solution:

- the problem is when creating 'MARIA_DB' user, you most likely created user that is not root
- Postal needs root privileges on MariaDB in order to spin new databases for each server

So, either adjust your yaml file to create & use root database user. Or you need to grant the different user you're using privileges on all databases starting with specified prefix in postal.yml file

Hope that helps...
