### ISSUE TITLE
Setup server on GCP, AWS or Azure without open 25 port.

### ISSUE THREAD

**Issue by pedrolarva** [postalhq/postal#1108]
Hello,

I am trying to setup an email relay server to approximately 15 million emails a day.
However, the place that is possible to use is on GCP, Azure or AWS, and both do not allow traffic on port 25.

how to conf server to send mail without port 25?

**Comment by willpower232** [comment]
Your using of port 25 won't be the problem here, you will likely find your Postal unable to connect to other servers on the standard ports.

I do not know much about GCP and Azure but on AWS you can request permission to send emails from your servers.

Other server providers are available so its down to you to ask if they can allow email sending.

**Comment by pedrolarva** [comment]
Thank you very much for responding.
You are consulted by GCP and Azure, and they cannot use the same.

I know that not all email servers will have this port 587, but the big ones will.

But the question is, is it possible for the postcard to send e-mails only using port 587?

**Comment by willpower232** [comment]
It may be possible but if your server provider isn't allowing email, they will likely have that port blocked as well.
