### ISSUE TITLE
Extending the webhook for Microsoft Teams

### ISSUE THREAD

**Issue by rbashish** [postalhq/postal#1147]
It would be great to see the webhook being extended to [**Microsoft Teams**](https://www.microsoft.com/en-in/microsoft-365/microsoft-teams/group-chat-software) channel to get the notification of every emails sent.
Is there a way to do this presently? If not please consider this as a **feature-request**.

Thanks!

**Comment by willpower232** [comment]
At the minute, there is no webhook process for new messages. This would make sense because software can send emails and record whatever information it needs to internally about that email, why it was sent etc, and then receive webhooks to find out what happened to the message.

Furthermore, I would say that notifying a chat-like software like Teams of each message sent and follow up information would create a very poor experience for many users of Postal, potentially thousands of notifications which would require significant effort to trawl through and understand.

If you need long-term reporting on Postal emails, you could increase the retention settings within the Postal UI or set up something yourself to suit your own needs.
