### ISSUE TITLE
Help with incoming emails?

### ISSUE THREAD

**Issue by giggioman00** [postalhq/postal#1160]
Hello, yesterday I installed this software on my VPS for the first time.
Everything went fine, I can succesfully send emails from my server.

The only problem is, I'm unable to receive incoming emails. I tried to reply to the test email I sent with postal, but these emails bounce. 

This is what I did. With WinSCP i edited the file located in /opt/postal/config/postal.yml and replaced and replaced every "example.com" domain with my own domain.
After that, I added the cname reutrning path and the mx setting on my domain's DNS.
After that I setup a routing in postal, so that every incoming email will be sent on another email. 

But it doesn't work. The bounce email says "Failure notice". Any idea what went wrong?

**Comment by willpower232** [comment]
Did you restart Postal when you changed the config file?

"No SMTP servers were available" can also mean that port 25 is not open or not accessible from the internet so it might be that either you or your server provider has a firewall or block in place.

**Comment by giggioman00** [comment]
Yes, restarted postal.
Port 25 seems open

**Comment by giggioman00** [comment]
Fixed, I forgot to set up an A record for the smpt and the mx.
By the way now I have a question, any idea how I can use Thunderbird with postal account? Because incoming emails are quite a mess as they are on the platform, really confusing

**Comment by wayneoutthere** [comment]
I have been searching for now a full week but I also cannot find the answer to this question: How do I use Postal as a 'real smtp server'? Or is this not the intention of it?  I can see it's very much designed to be a kind of 'marketing relay' service, which is great, but I was planning to use it with a 'boring old email client' and create boring name@domain email addresses for our business.  Is this not possible?  I think it must be possible?  If there is any kind of guide for 'how to set up inbound email addresses using only Postal SMTP" that would be awesome.  Thanks for any help!! :)

**Comment by willpower232** [comment]
Postal has absolutely no concept of an inbox so does not fully integrate with a traditional email setup. You could set the outgoing details in your mail client to a Postal credential but without a very specific middleman program to store messages and present them as POP/IMAP, you will not be able to handle incoming email in an email client.

**Comment by wayneoutthere** [comment]
Perfect, thanks, @willpower232.  This is really good and I think should be more clear.  I will actually be using Postal because I'm really impressed with it.  I just didn't properly understand what it was and what it does.  I think this kind of verbiage (totally raw, quick example) might help:  "Snap on your email marketing tool to this simple and GUI. " or 'Programmers - looking for a tool to send your emails through complete with API, etc etc?"  And then some other section that says boldy "This is *not* an office-style email SMTP server. If you're looking for that try ____ (insert favourite recommended solution ?)  Anyway, there's all my quick suggestions.  Feel free to like them, toss them, love them or hate them, but one thing is for sure - nice work on this! I will blog my super, duper long tutorial about how to install it regardless of whether I use it.  Maybe I"ll post it back in this thread too if I remember.  Thanks folks!

**Comment by ismayilmalik** [comment]
> Fixed, I forgot to set up an A record for the smpt and the mx.
> By the way now I have a question, any idea how I can use Thunderbird with postal account? Because incoming emails are quite a mess as they are on the platform, really confusing

How did you fix? Having same issue(((

**Comment by adamcooke** [comment]
Postal is not designed to be used with any mail client really.

**Comment by Xenomorph07** [comment]
> > Fixed, I forgot to set up an A record for the smpt and the mx.
> > By the way now I have a question, any idea how I can use Thunderbird with postal account? Because incoming emails are quite a mess as they are on the platform, really confusing
> 
> How did you fix? Having same issue(((

please tell what A record should I add

should I add one for mx.example.postal.com to point to my server ip ?

**Comment by Xenomorph07** [comment]
> @Xenomorph07 same problem. Yiu solve it?

No, I wasn't able to solve the issue 
following this I just moved and migrated towards mailcow because it was blocking go live for us

**Comment by Igcorreia** [comment]
My solution was, as described above. 
I had to create a A record for the mx.server.com
