### ISSUE TITLE
Send emails for different SMTP credentials using Postal 

### ISSUE THREAD

**Issue by rbashish** [postalhq/postal#1185]
Hi, 
I have two questions for Postal:

1. Company 'X' has given us their SMTP Credential to send emails from our application. Is it possible to send using Postal so that we can track the emails?
2. Also can Postal act as SMTP Proxy?

**Comment by luison** [comment]
As I have a similar question and I am uncertain if this kind of generic questions belong here I'll add it in case it can also be answered. 

In our case, we have several Google Apps domains we use for delivery and receiving emails but we want to incorporate a middle process that can act as a proxy and allow us transactional webhooks to our apps similar to mailgun.  We are not that concerned in incoming email as sending process.

In this scenario we would need to be able to send messages to postal from our apps via JSON and the add two actions so that can generate: 
1.- use postals MessageSent event to register that email on another database or app
2.- deliver the message ideally via Googles SMTP

Is this possible in postal?

Thanks.

Sidenote... screenshots images are not working on the github page.

**Comment by willpower232** [comment]
I think that Postal can send messages through a proxy but only if the proxy allows unauthenticated connections. I don't believe that Postal will work for your particular use cases because of its inability to authenticate when connecting to a proxy.

I'm not familiar with the process but I imagine you could add another process between Postal and your desired proxy to handle the authentication, theres a lot of interesting discussion in #48
