### ISSUE TITLE
delete

### ISSUE THREAD

**Issue by js001** [postalhq/postal#1186]
delete

**Comment by js001** [comment]
how to send email to inbox folder, not spam folder?

**Comment by js001** [comment]
how to send email to inbox folder, not spam folder?

**Comment by ilovepancakes95** [comment]
This isn't the point of Postal. You still need a mail server setup somewhere to properly manage mailboxes/webmail.

**Comment by js001** [comment]
where is webmail?

**Comment by js001** [comment]
i forgot admin login password? how to reset?

**Comment by willpower232** [comment]
>  i can access postal in localhost.
Postal should be hosted on a server with internet access from a provider such as Digital Ocean, AWS, etc, etc. You should do this first before trying to resolve other problems.

That said, here are the other answers to your questions.

As mentioned above, there is no concept of inboxes within Postal, you will not be able to read messages in a webmail interface or from an email program without making something to handle that part.

Messages can end up in your spam folder for a number of reasons, most likely is your internet connection is not using a trustable IP address as is often the case with regular internet connections

You can use spamassassin to scan messages if you wish, the details should be in the wiki.

If you create an SMTP credential with Postal, you can use any SMTP-friendly email command to send messages. If you create an API credential, you could write a more complicated command with `curl` or similar.

If you have configured your Postal to send messages via itself in `postal.yml` then you should be able to use the forgotten password link.

Honestly, it sounds like you would be better suited to use something like https://mailinabox.email/ instead of Postal.

**Comment by js001** [comment]
how to receive email with postal? where is email address to receive email?

**Comment by willpower232** [comment]
Mail is received and handled with routes where you can specify the email address you want to receive email at.

**Comment by js001** [comment]
how to configure routes to received email?

**Comment by js001** [comment]
how to access server on port 25?

**Comment by willpower232** [comment]
You should be able to configure routes in the web UI of Postal. The credentials page in the UI can also tell you how to connect.

**Comment by js001** [comment]
what is this ip address - https://github.com/postalhq/postal/wiki/Domains-&-DNS-Configuration ? public ip address ipv4 just have only one address. why in document write have two ip address: 1-IPv4 address for management, SMTP and other traffic ; 2-IPv4 address for the "fast" web server (used for tracking). is send email with domain need to configure local ip or public ip? in document write local ip address.

**Comment by js001** [comment]
what is change to public ip address? /opt/postal/config/postal.yml
"
web:
  host: postal.example.com
  # The protocol that requests to the management interface should happen on
  protocol: https

main_db:
  # Specify the connection details for your MySQL database
  host: localhost
  username: postal
  password: password
  database: postal

message_db:
  # Specify the connection details for your MySQL server that will be house the
  # message databases for mail servers.
  host: localhost
  username: postal
  password: password
  prefix: postal

rabbitmq:
  # Specify the connection details for your RabbitMQ server.
  host: 127.0.0.1
  username: postal
  password: password
  vhost: /postal
  
dns:
  # Specifies the DNS record that you have configured. Refer to the documentation at
  # https://github.com/atech/postal/wiki/Domains-&-DNS-Configuration for further
  # information about these.
  mx_records:
    - mx.postal.example.com
  smtp_server_hostname: postal.example.com
  spf_include: spf.postal.example.com
  return_path: rp.postal.example.com
  route_domain: routes.postal.example.com
  track_domain: track.postal.example.com
"

**Comment by js001** [comment]
i send email in postal to gmail then email received in gmail's spam box. how to send to main box?
