### ISSUE TITLE
Integrate Postal with Exim on WHM

### ISSUE THREAD

**Issue by helixcloud1337** [postalhq/postal#1214]
Hi, i have VPS installed WHM

How i can integrate postal with Exim on WHM Server? i have try Sendgrid on Exim that have configuration like this : 

```
Section: AUTH
 sendgrid_login:
 driver = plaintext
 public_name = LOGIN
 client_send = : user : pass

```
```
Section: PREROUTERS
 send_via_sendgrid:
 driver = manualroute
 domains = ! +local_domains
 transport = sendgrid_smtp
 route_list = "* smtp.sendgrid.net::587 byname"
 host_find_failed = defer
 no_more
```

```
Section: TRANSPORTSTART
 sendgrid_smtp:
 driver = smtp
 hosts = smtp.sendgrid.net
 hosts_require_auth = smtp.sendgrid.net
 hosts_require_tls = smtp.sendgrid.net
```

It's possible to make like this on postal? if possible, how i can configure like that?

**Comment by willpower232** [comment]
At the minute, you are intending to send emails from your server via sendgrid but you want to send via postal instead?

I believe Postal might work like this however since Postal would have to be installed on a server by yourselves, you would not see any benefit from using Postal in this configuration. If you need your emails to be sent from a different server/IP address, you could use another installation of exim or a different mail server.

If you are hoping to make use of Postals features in your applications, it would be more appropriate to have them use Postal directly rather than sending via exim.
