### ISSUE TITLE
Having Trouble Setting Up Return Path for Postal SMTP

### ISSUE THREAD

**Issue by jamesjosh912** [postalhq/postal#1215]
I was able to set up the DKIM, SPF, and MX records successfully (have the checkmarks), but I still have a grey check next to return path)
![return path issue](https://user-images.githubusercontent.com/68710900/93631734-b803b600-f9b1-11ea-8a3c-a7042d0d9851.png)

"    This is optional but we recommend adding this to improve deliverability. You should add a CNAME record at psrp.gtplife.com to point to the hostname below.

rp.postal.example.com   "

I did exactly that. I created a CNAME record in godaddy with the "name" as psrp.gtplife.com and with the "value" as rp.postal.example.com  and the "TTL" as 1 hour. What could be the issue?

**Comment by Igcorreia** [comment]
2 things that you may have incorrect, one is that is I am not mistaken, the return path needs a different IP address to make it work.

But in your case, to validate your domain look like you primary domain in gtplife.com, so the correct values should be:

CNAME      psrp      rp.postal.gtplife.com     1H

notice that I removed the domain form the NAME because that is the prefix and added/change example.com to your domain.

**Comment by jamesjosh912** [comment]
Ok, now I am getting these errors:
For gtplife.com, I have a green check for the mxrecords, but not for the
return path. For gtplife.co, I am getting a check mark for the return path,
but not the mx records. What is the issue?

**Comment by jamesjosh912** [comment]
Those are two different domains I am setting up by the way

**Comment by Igcorreia** [comment]
Also, you need to have into consideration DNS propagation. I notice that you have a 1-hour configuration in TTL. For a quick check change it to custom to a 600 seconds propagation (10 mnts). Once you get your domains checked, change it back to AUTO or 1 Hour.

Postal validates the Domains to perfection in my case. The problem is that the description is not perfect. 

It is different to validate a subdomain than a domain:

## for Domain (type | name | value | ttl)

SPF: TXT | @ | SPF1...  | 1hour 
DKIM: TXT | ...domainley | DKIMVALUE | 1 hour
RP: CNAME | @ | rp.... | 1 hour
MX: MX | @ | mx... | 1 hour

## for SubDomains (type | name | value | ttl)

SPF: TXT | **subdomain** | SPF1...  | 1hour 
DKIM: TXT | ...domainley.**subdomain** | DKIMVALUE | 1 hour
RP: CNAME | **subdomain** | rp.... | 1 hour
MX: MX | **subdomain** | mx... | 1 hour

**Comment by willpower232** [comment]
It is highly unlikely that example.com is your correct domain name. You should set up postal.yml so that it has real domain names, not example.com and restart Postal so that the UI is updated to give you correct information.

**Comment by jamesjosh912** [comment]
I'm confused. What exactly am I doing wrong? Here is a screenshot of my
inputs:

**Comment by jamesjosh912** [comment]
I tried putting in the 600 seconds as you suggested, but it didn't do
anything, so I put it back to 1 hour.

**Comment by jamesjosh912** [comment]
Here's a better screenshot with 600 secs, but it doesn't work

**Comment by willpower232** [comment]
Your screenshots are not coming through unfortunately.

You need to update the config file to replace the references to `example.com` with your own domain name and then restart Postal to apply it.

You can see the defaults here https://github.com/postalhq/postal/blob/master/config/postal.defaults.yml#L91-L98
