### ISSUE TITLE
stability, versions, update strategy

### ISSUE THREAD

**Issue by siebertm** [postalhq/postal#1217]
In order to properly evaluate the usage of postal, how would one know when a new version is released? Whats the general strategy on stable/beta/master? Looking at the stable channel, it looks like this is lagging more than a year behind master, but both are still version "1.0.0". 

I could not find any info on the general release strategy here, so I'm heading out here...

Thanks!

**Comment by tomlobato** [comment]
Hi Michael, I currently use Postal, although thats the same I feel here. Did you find another good candidate?

**Comment by Igcorreia** [comment]
Same here my friends. Can anyone give us a clue about what is happening? Also some features I had to manually implement from the suggest pull requests. It may break my integrations in the future :/

**Comment by willpower232** [comment]
We have been using a git-cloned copy of Postal since its release, paying attention to new commits, PRs, and problems, and then updating individual files as necessary. I believe that the latest versions are cut from the same code but with the version reference but I'm not sure how the releases are documented.

It would be nicer if that was documented in here however I guess for now we're treating it as a rolling release efectively.

**Comment by catphish** [comment]
I'm afraid there is currently no well defined process to schedule or announce releases. We try to do releases whenever we feel they are justified. There will certainly be one soon as there have been some bugfixes recently, but that's about all I can promise.
