### ISSUE TITLE
FROM header changes more than once

### ISSUE THREAD

**Issue by stephancasas** [postalhq/postal#1274]
Hello,

I'm currently troubleshooting a `530 From/Sender name is not valid` error and am combing through SMTP logs to get a better understanding of the issue.

<pre><code>[34m[smtp.1:2673][0m [2020-12-21T20:17:56.546] DEBUG -- : <strong>[UIIQHB]</strong> [34m=> 235 Granted for acme/ent-relay[0m
</code></pre>

Provided that the above-emboldened attribute is the unique transaction/exchange ID, is it normal to see the `MAIL FROM` attribute updated multiple times for one transaction? I'm seeing the following on a recurring basis:

<pre><code>[34m[smtp.1:2673][0m [2020-12-22T20:59:07.741] DEBUG -- : [IWH2TC] [32m<= <strong>MAIL FROM:&lt;jason@acme.com&gt;</strong>[0m</code>
<code>[34m[smtp.1:2673][0m [2020-12-22T20:59:08.332] DEBUG -- : [IWH2TC] [32m<= <strong>MAIL FROM:&lt;daniel@acme.com&gt;</strong>[0m</code>
<code>[34m[smtp.1:2673][0m [2020-12-22T20:59:11.282] DEBUG -- : [IWH2TC] [32m<= <strong>MAIL FROM:&lt;sarah@acme.com&gt;</strong>[0m</code>
<code>[34m[smtp.1:2673][0m [2020-12-22T20:59:12.759] DEBUG -- : [IWH2TC] [32m<= <strong>MAIL FROM:&lt;tristian@example.com&gt;</strong>[0m</code></pre>

What I find very interesting about this is that the last entry in the log indicates a change in domain. While this Postal instance does in-fact have two organizations on it, I'm not sure I understand why a sender from one domain would spill into the mail traffic for the other.

I created a small tool in Node.JS for log inspection and from what I can gather, the only transactions reaching successful dispositions are the ones where the `MAIL FROM` attribute is updated only once. All other failed transactions show multiple log entries where this attribute is being changed.

Both organizations dispatch to Postal via EXIM relay, so if it's necessary for the headers to be manipulated in some way or another to prevent this from occurring, this is not an issue for us.

Any insight on this matter is greatly appreciated.

Thanks!

**Comment by willpower232** [comment]
That is a good spot, you can see how Postal handles `mail from` here https://github.com/postalhq/postal/blob/2595481b266199d8e29347dea2764f2c10202805/lib/postal/smtp_server/client.rb#L231-L247

I believe that each individual message should only have one `mail from` so the fact there are multiple in your situation implies that your relay isn't completing one connection before starting another or is potentially misconfigured in another way.

I don't fully understand what is happening in that code but I imagine that the recorded `mail from` is being replaced until the sending software moves on to the next command. The error you're seeing is because the found domain from `mail from` doesn't match the domains in the same server as the credential key, which is understandable if multiple are being sent.

**Comment by stephancasas** [comment]
Thank you for the swift response. Knowing which routine does this interpretation helps significantly. I'm going to run a series of tests and see what sort of patterns I can identify.

I'll report back here once I've nailed something. Thanks!

**Comment by stephancasas** [comment]
I've completed some tests and am very surprised by what I've found.

> #### TL;DR
> Maybe having two tenants using the same EXIM router caused this issue?

The production instance of Postal that we're using relays mail sent to it from a cPanel/WHM server running EXIM as the mail transfer agent<sup>**</sup>. The cPanel server has two tenants on it and in Postal, each tenant is configured as a separate organization each with its own mail server and set of SMTP credentials.

<sup>**After a misconfigured WooCommerce incident, the cPanel server's IP address reputation was in the can, so relay was our only immediate choice for getting up and running quickly. Postal was a dream to setup and has been superb.</sup>

In our initial setup, only one EXIM router was configured to dispatch mail from EXIM to Postal, but a lookup string expansion was used to ensure that each connection supplied the correct set of credentials:

```rb
#ROUTER
send_via_postal:
  driver = manualroute
  senders = *@example.com : *@acme.com
  domains = ! +local_domains
  transport = postal_smtp
  route_list = * postal.example.com
  no_more

#AUTH
postal_login:
  driver = plaintext
  public_name = LOGIN
  client_send = : ${extract{user}{${lookup{$sender_address_domain}lsearch{/etc/postalcredentials}}}}: \
                  ${extract{pass}{${lookup{$sender_address_domain}lsearch{/etc/postalcredentials}}}}
```

Operating under the assumption that only one message would be sent per SMTP connection to Postal, this would have appeared to work correctly. However, that doesn't seem to be what was happening.

Based on the log data from Postal, it looks like a connection would open to transfer a message for *example.com*, and while that connection was open, a message for *acme.com* would also be transferred while still under the connection authenticated for *example.com*. Of course, as you've seen from the initial post, this would update the `MAIL FROM` attribute, and cause the message to fail delivery with code `530`.

I expected that concurrent transfers like this would only take place if the messages were received by EXIM at the same time, so I programmed a filter to freeze all outbound messages, and then used the CLI tools to release for transfer to Postal all at once. Contrary to my expectation, each message was sent over its own SMTP connection, and Postal processed the deliveries normally.

At this point, I'm not entirely certain why this issue was occurring. There's a possibility that my test procedure is not bulletproof, but I'm relatively confident it's simulating the conditions I'm trying to replicate. What I hope will be the final nail in the coffin is the separation of the two tenants' traffic into two different routers both pointed at Postal. If EXIM *is* transferring more than one message per SMTP connection, then I should think that two different routers would ensure that each tenants' messages at least travel over the correctly-authenticated connection.

I'd be curious to know your thoughts on this. Should more than one message per SMTP connection be getting transferred like this?

Cheers and thanks again,
Stephan

**Comment by willpower232** [comment]
I think it is fine to send more than one message per SMTP connection but one message needs to be fully transferred before the next one can start unless there is some kind of threading process to allow multiple messages to be transferred simultaneously.

You can see in that file how the connection can be re used to send further messages but the messages must match the domain used in the original credential.

It may be that exim has interpreted the postal connection as a more low level gateway that can handle everything thrown at it rather than something which needs a bit more care and attention.

Exim may be expecting some kind of threading behaviour which postal doesn't yet implement. You could have a look at #751 but I'm not sure how useful that will be.

Your example suggested that exim was trying to send four messages simultaneously so something to be aware of would be some queuing behaviour at your end to ensure exim was able to properly separate messages.

I don't really know much about exim but hope some of that was useful!

**Comment by stephancasas** [comment]
Quite helpful, yes — thank you!

I configured EXIM to treat each connection to Postal as a separate router, even though they both are required to share the same authenticator. In this way, EXIM opens one connection to Postal per collection of messages it needs to send per domain:

```rb
example_send_via_postal:
  driver = manualroute
  senders = *@example.com : *@email.example.com
  domains = ! +local_domains
  transport = example_postal_smtp
  route_list = * postal.example.com
  no_more

acme_send_via_postal:
  driver = manualroute
  senders = *@acme.com : *@mail.acme.com : *@cloud.acme.com
  domains = ! +local_domains
  transport = acme_postal_smtp
  route_list = * postal.example.com
  no_more
```

Since implementing this change, I've kept an eye on logs for a week and no unexpected failures have occurred. Things are working smoother than ever.

Thank you for your help with this! :sunglasses:
