### ISSUE TITLE
Expected response code "354" but got code "530", with message "530 Authentication required".

### ISSUE THREAD

**Issue by plamenh** [postalhq/postal#1315]
Title says it all. Get this only occasionally.

**Comment by willpower232** [comment]
Presumably you are trying to use SMTP? What are you using to send the messages?

**Comment by plamenh** [comment]
Symfony Mailer (https://github.com/symfony/mailer)

**Comment by willpower232** [comment]
If you're only seeing this message occasionally, it sounds like you have authentication working correctly but it might be that when you're sending messages, some of them fail to send and your connection to Postal is reused badly or something like that.

If you're using PHP, you may have a better time with the API and https://github.com/krystal/postal-php

If you want to keep using SMTP, there must be some issue with how you are sending messages. Are you sending a lot at a time?

**Comment by plamenh** [comment]
Yes, occasionally we send a lot at a time. The issue does not seem related to this, however. Sometimes we get it with a batch of 20 e-mails, sometimes it does not happen with 200.

Unfortunately, using the postal-php bundle will complicate our implementation a lot.

So you're thinking that Symfony Mailer tries to (wrongfully) reuse the connection, while Postal expects a new authentication request?

**Comment by willpower232** [comment]
I assume that at some point you are using a loop in the code to send all the messages. If the loop does not complete successfully before starting the next message then that would create this kind of situation. The more emails in a batch, the greater chance of something like this happening but as you say, it could happen at any time.

If you're able to watch the logs on your Postal server when trying to send messages you should be able to see the SMTP commands it receives and in what order so that would give you a clue as to where things stop working.
