### ISSUE TITLE
Selection of domains

### ISSUE THREAD

**Issue by gitaayush** [postalhq/postal#1325]
Can any one tell me  the difference between **below domain** ??

![image](https://user-images.githubusercontent.com/47238161/113104983-d54af400-9220-11eb-9b48-17bb725edca0.png)

**and this domain** 

![image](https://user-images.githubusercontent.com/47238161/113105114-f4498600-9220-11eb-986d-7eb8f7957ff7.png)

Organization -> Domains and
Mail server -> Domains 

When I add domains in Organization -> Domains, it is not shown in Mail Sever -> Domains. Can any one tell me the difference between these two domains

**Comment by willpower232** [comment]
Domains in the organisation (the first screenshot) apply to all mail servers in that organisation.

For example, this is handy if you wanted to put a development domain so that you can test each mail server separately or if you wanted to put your main company domain in the organisation and separate out each department or application with a mail server.

**Comment by gitaayush** [comment]
@willpower232  Thank you for your response. Its clear now.
