### ISSUE TITLE
Delivery attempted over ipv6 which is disabled

### ISSUE THREAD

**Issue by pcarr-m3** [postalhq/postal#1362]
I'm getting this error delivering to Comcast:
```
Permanent SMTP delivery error when sending to mx1.comcast.net (2001:558:fe16:1b::15) Recipient added to suppression list (too many hard fails).
```
However ipv6 is disabled on my system, /etc/gai.conf returns ipv4 before ipv6, yet all connections to Comcast are attempted to the ipv6 address.  This is running on Ubuntu 18.04 running in AWS with an EIP.  My DNS resolver is dnsmasq.  I have the following sysctl options configured:
```
net.ipv6.conf.all.disable_ipv6=1
net.ipv6.conf.default.disable_ipv6=1
net.ipv6.conf.lo.disable_ipv6=1
```
I am running 1.0.0-2595481b26-stable.

**Comment by willpower232** [comment]
can you still see `::` or `tcp6` or `udp6` entries if you run `netstat -lnp`?

**Comment by pcarr-m3** [comment]
Yes I do.  I was able to play around with dnsmasq more and did git the host returned as an IPv4 address.  Sadly it did not help, I think Comcast has blocked the IP.  I was hoping it was just a problem with their IPv6 endpoint.

I am going to close this as at this point I am confident it's not an issue with Postal itself.

**Comment by willpower232** [comment]
I'll just add that if you can still see those entries in netstat, you haven't disabled IPv6 as much as you think.

You would have to investigate the hard fails specifically to see what the underlying problem is. Disabling IPv6 is not recommended for general future proofing but we're still in a weird middle ground so your use case might not leave you with many options.
