### ISSUE TITLE
Postal cluster

### ISSUE THREAD

**Issue by diegolr62** [postalhq/postal#1388]
We are planning a big postal deployment in a cluster way. The DB server will be separated from the app servers which will run rabbitmq, nginx , and ruby. We have checked that the postal database has everything needed to run several servers with the same configuration provided that every cluster member would connect to the db server.

Our concern is naming and  ip addressing. Should every cluster member have the same name, eg: postal.domain.com ?? And obviously the ip addresses will be different, is there any problem with that? Our deploy will include a Cisco router configured as load balancer (in LSB mode).

Please advice us or let us know any suggestion to accomplish this project.
Regards
Diego

**Comment by willpower232** [comment]
If all your traffic is going _out_ via the router then in theory you can use its IP address as all your DNS records otherwise you would need to likely need to list multiple IP addresses in the DNS records which could be annoying to manage.

I think spam checkers will get annoyed if the server name doesn't match the domain name in one of the email headers so it will be important to get that right but I'm not sure if that is a Postal configuration thing or a server hostname thing.

There is nothing stopping you from running different parts of Postal on different members of the cluster if you have the numbers so that would also affect the DNS records.

Does that make sense?

**Comment by diegolr62** [comment]
Thanks for your response.  Yes, that will be the case, at the end, after passing out the load balancer/router, for the world the system will be seen as one ip address.  What we will try to deploy is a black box with an smtp server (several postal servers inside actually) exposed.

Regards,
Diego
