### ISSUE TITLE
Tracking

### ISSUE THREAD

**Issue by AirpayMatt** [postalhq/postal#351]
Hi Guys,

How can we add tracking to email sent via postal.

1. Did the email get delivered to the recipients
2. To figure if the email was opened by the recipient, 
3. did it go into spam or got bounced.
etc

Thanks for your help in advance.

Thanks & Regards
Matt

**Comment by shopglobal** [comment]
I believe this is in DNS settings

**Comment by willpower232** [comment]
You will need to enable Click Tracking which does involve a bit of DNS. Please see https://github.com/atech/postal/wiki/Click-&-Open-Tracking

If you want your application to inform you of the status of a message (instead of Postal), you will need to set up Webhooks. Please see https://github.com/atech/postal/wiki/Webhook-Events-&-Payloads
