### ISSUE TITLE
Slow down send rate

### ISSUE THREAD

**Issue by shawntremere** [postalhq/postal#488]
What is the best way to slow down the send rate?
Reduce the number of worker you use? Anything else?

**Comment by willpower232** [comment]
Reducing the workers should slow things down but if you really don't want to send emails that fast, you might find better results with sending emails in more spread out batches or having some kind of queuing feature in your application before they get to Postal.

**Comment by fgjohnson** [comment]
Thanks Will,
I work with Shawn.
Quote:
`sending emails in more spread out batches or having some kind of queuing feature in your application`

How can we batch emails in Postal? 
... or does this need to be done at our application?  

Different mail servers have different "rates of acceptance"... so it would be nice if that was available in Postal.

Thanks

**Comment by willpower232** [comment]
Postal is more of a transactional email system and sends email when it is told to rather than a marketing or broadcasting style system.

If you are sending email in such a significant volume that it causes issues with the systems you email then forming a queue within your application is currently the only way to remedy the issue.
