### ISSUE TITLE
HardFail Limit

### ISSUE THREAD

**Issue by sandeep28saxena** [postalhq/postal#560]
Currently if an email hard fails twice its added to suppression list. How can I increase this limit. 

Also can I configure after how many days emails in suppression list would be retried ?

**Comment by willpower232** [comment]
I don't believe the hard fails limit is currently customisable presumably because the hard fails are more permanent than the soft fails.

I don't think the days count on the suppression list is configurable either at the minute.

If a message is in the suppression list, messages to it will be held. If you know the message will be able to be sent (i.e. the reason for the hard fail or soft fail has been fixed) you can release the message manually and its successful delivery should remove it from the list.

**Comment by sandeep28saxena** [comment]
ok I saw in another issue https://github.com/atech/postal/issues/58 adamcooke said that hard fail is customizable. 

Also I was looking to decrease the limit of days itself or a feature to bulk remove everything in suppression.  My suppression list stands very tall right now.

**Comment by mattmartincouk** [comment]
I think there is a typo of either meaning neither given the latter bit of that whole sentence.

**Comment by willpower232** [comment]
For whatever reason, it looks like only the soft fails limit is customisable.

If an email address is on the suppression list, that address is encountering prolonged issues so it doesn't make sense to clear the whole thing.

If you know which addresses should be working, you can release the held messages to that address and it should get cleared if there isn't an issue any more.
