### ISSUE TITLE
want to setup postal on scale server

### ISSUE THREAD

**Issue by ngoyal16** [postalhq/postal#694]
how to set up postal with the main server which will receive the mails child server which sends emails out. tracking server properly on AWS on the scale. 

1. multiple instances so that can send emails out
2. single big instance to get the mails in
3. RDS for database
4. enabled click and tracking system
5. if possible use amazonmq for messaging

**Comment by willpower232** [comment]
This mostly appears to be possible (https://github.com/atech/postal/issues/334#issuecomment-326765678 https://github.com/atech/postal/issues/573#issuecomment-414959335) but there are a few caveats based on your list.

The server receiving the emails will be the one(s) mentioned in the MX records so this could be any or all of your servers that have Postal installed on. Same for click tracking but click tracking would require a separate IP address on each server it was installed on.

I don't think you'll be able to use AWS RDS because postal needs the ability to create other databases and I don't think thats possible unless you give postal the master DB credentials which is very inadvisable.

I believe it would be a fair amount of work to swap RabbitMQ for the AWS equivalent and probably not a priority for the rest of the project.

Finally, each server sending email would need reverse DNS setting up by AWS themselves, see https://github.com/atech/postal/issues/192

**Comment by ngoyal16** [comment]
@willpower232 
1. MySQL or MariaDB is not my concern I can have one dedicated RDS instance to this 
2. I Will have one common server which will receive the email

now, 
1. how will I use AmazonMQ as RabbitMQ any reference to that?
2. how will I connect workers to the main instance. 
3. the workers should only run on slave instance not on the master one
4. and how to set up tracking domain

**Comment by ngoyal16** [comment]
can you help me to setup this cluster
