### ISSUE TITLE
Click tracking error

### ISSUE THREAD

**Issue by criskolkman** [postalhq/postal#707]
Hello,

Click tracking seems to be working (the URLs are being edited to the click domain) but I get the following message:

Forbidden
You don't have permission to access /abotgs/rriuOMHr on this server.

What could be the issue?

Do I have to open ports 5010 and 5011 to the secondary IP I'm using for the click tracking (or maybe other ports)?

**Comment by criskolkman** [comment]
Click tracking is working after adding the correct cname domain in my firewall, but open tracking is not working.
Also it is quite strange to add clicking domains, because I added a link to Google in my email but that is not being tracked.

**Comment by willpower232** [comment]
Having a firewall such as your current one running in front of the server is likely not optimal as you have already surmised so definitely not recommended.

When you say tracking is not working, are the links in your email being changed to the tracking domain?

**Comment by criskolkman** [comment]
Hello,

No like I said the click tracking is working, but when an email is being opened (being read), that tracking is not working.

And also like I said:
Also it is quite strange to add clicking domains, because I added a link to Google in my email but that is not being tracked.

It's just not normal that you have to add domains to track the clicking.
When I send an email to someone with a like to Youtube or whatever, that clicking has to be tracked as well.

**Comment by willpower232** [comment]
I'm not sure you understand how this feature works. You need at least one tracking domain per domain you want to enable tracking on. Tracking domains should point at your Postal installations tracking IP. If you are sending email from `example.com`, your tracking domain could be `track.example.com`.

Any links in messages are then replaced with links to `track.example.com` and a path that represents the link so that Postal can record the click and forward the user to the intended destination.

Once you have added your tracking domain, you should see that domain replacing links in the messages that get sent.

Does that help?

**Comment by criskolkman** [comment]
Hello,

I have added that but I see the issue now.
A mail being send from Outlook is not being converted to click tracking URL.
When I send the same URL's via Exchange OWA, the conversion is correct and the clicks are being tracked.

Also:
![image](https://user-images.githubusercontent.com/17678609/49795889-743f3f80-fd3b-11e8-8015-4d8f05e008dd.png)

Why is it that open tracking is being send to a webhook only while it **should** also appear in the Message Activity?

**Comment by criskolkman** [comment]
Okay just found out something else.
Mails being send from Exchange OWA are being "open tracked" but mails send through Outlook or a webportal are not being "open tracked":

![image](https://user-images.githubusercontent.com/17678609/49796648-8fab4a00-fd3d-11e8-8096-b08e9e3f4bbc.png)
