### ISSUE TITLE
Can't disable https and use http

### ISSUE THREAD

**Issue by gonace** [postalhq/postal#869]
Hi
I've installed via the Quick Install option on Ubuntu and edited the `config/postal.yml` configuration file and changed the `protocol` option under `web` to `http`.

I also edited the `app/config/environments/production.rb` to `config.force_ssl = false`

Changed the nginx configuration so to list on port 80 and not redirect to 443

But I'm still being redirected to https,

Postal rails.log give me this:
```
07:23:24 web.1              | => [web.1:114382] [2019-08-17T07:23:24.927] INFO -- : Redirected to https://xxx.xxx.xxx.xxx/login?return_to=%2F
07:23:24 web.1              | => [web.1:114382] [2019-08-17T07:23:24.927] INFO -- : Filter chain halted as :login_required rendered or redirected
07:23:24 web.1              | => [web.1:114382] [2019-08-17T07:23:24.927] INFO -- : Completed 302 Found in 4ms (ActiveRecord: 0.6ms)
```

**Comment by willpower232** [comment]
Have you restarted both Postal and nginx (or even the entire server) since you made the changes?

**Comment by gonace** [comment]
Hi, yes restart and even tried a reboot, works as soon as HTTPS is enabled again.

**Comment by nmanley** [comment]
I'm not a ruby developer.

but try enabling rails debug.

config.action_view.debug_rjs = true
config.logger = Logger.new(STDOUT)
config.logger = Log4r::Logger.new("Application Log")

grabbed from the following website.
https://guides.rubyonrails.org/v3.0/debugging_rails_applications.html

**Comment by willpower232** [comment]
I have been using custom ports on our Postal testing server, https://postalserver:444 to make space for the click tracking.

Now if I try to go back to the normal ports, I find myself redirected to 444 essentially replicating the above issue.

Presumably there is a cache somewhere or I hardcoded the port but I can't find it any more :-/

**Comment by nmanley** [comment]
@willpower232 where is the 30x happening? Browser, nginx/apache or ruby?

Try searching for 444 in web root?
find / -name '*.rb' -exec grep -Hn "444" {} \;

**Comment by willpower232** [comment]
As highlighted by @gonace the redirect includes the login URI and query string which makes me think the redirect comes from within Rails, most likely here https://github.com/atech/postal/blob/634d3af59d392e84bdcd2b843b427f3a79d3ff4c/app/controllers/application_controller.rb#L19

There is no mention of the URL or 444 in the ruby files so presumably its cached somewhere more specific.

I'm willing to bet that atech, or someone who knows Rails, will know where the issue is. I hasten to add this isn't a real problem for us but someone will eventually need to move Postal to a new URL and having the old one embedded somewhere isn't a good thing.
