### ISSUE TITLE
Postal should filter spoofed emails

### ISSUE THREAD

**Issue by Nekiono** [postalhq/postal#902]
Since postal can be used to route emails, an email sent to a postal server could become a non-spoofed email, even though it is.

As in
Route: a@mydomain.com => private@gmail.com
Someone sends an email from a spoofed "a@mydomain.com" to a@mydomain.com, which gets forwarded to private@gmail.com; but since postal didn't notice that it's spoofed, the SPF records now line up (since technically now postal is the sender).

I just had a case of this behavior, and think this could be a potential spam/security issue.

**Comment by willpower232** [comment]
Interesting, would you be able to detail the settings for your server and your general email flow setup?

**Comment by Nekiono** [comment]
_Since I run this server for a friend, and I care about their privacy, the email/domain names here will not be the actual names._

The mail server has a verified domain called artistdomain.com with SPF, DKIM, and MX records set. The SPF records only allow postal. [I cloned the SPF record on postal.cloudy.gg, incase you want to have a look at it.](https://bir.bz/1Iu2D)

I have three address endpoints, rec-a@gmail.com, rec-b@gmail.com, and rec-c@gmail.com.

A route, owner@artistdomain.com has the following settings:

- Endpoint: rec-a@gmail.com
- Additional Endpoints: rec-b@gmail.com, rec-c@gmail.com
- Spam Mode: Mark

Some more details:
- Screenshot of the email in the incoming tab https://bir.bz/hLQ2j
- Spam Status https://bir.bz/TRKDr https://bir.bz/J6XQ8
- The email contents (obviously fake; spam) https://bir.bz/1VkX2

Thanks for the quick reply!

**Comment by catphish** [comment]
If spamassassin didn't detect that the message was SPAM, there's not really much we can do about it This whole situation is irritating, but is an unavoidable side-effect of how verification has been bolted onto emails. In order to forward an email, we must re-sign it, so SPAM will suddenly look like legitimate email. The only solution is to try to detect SPAM and *not* forward it, but is seems in the specific case above, this was not possible, or perhaps your spamassassin is not set up correctly.

**Comment by Nekiono** [comment]
Hi,
Sorry for the late reply.
I've checked their SA setup and it seems it was misconfigured.
I'll close this for now - will reopen if this occurs with a correct SA setup.

**Comment by willpower232** [comment]
Thanks for letting us know
