### ISSUE TITLE
Configure Loadbalancing in Postal

### ISSUE THREAD

**Issue by bpareek9694** [postalhq/postal#947]
Hello Community,

I've configure postal in two server,

How can i configure both server, When Server1 is down the mail will be send by Server2.
When Server2 is down the mail is send by server1.

How can i configure Load balance (using HA Proxy) on both Server?

Please Help Me

**Comment by willpower232** [comment]
I'm not sure that this functionality is possible without something monitoring both servers and controlling the processes.

It would be less complicated to run two servers at the same time that share a Rabbit MQ server and database server and any messages that werent picked up by the first server, because it was down, could be handled by the second server.
