### ISSUE TITLE
ip tracking?

### ISSUE THREAD

**Issue by epipheus** [postalhq/postal#951]
Postal tracks opens and clicks I assume with a pixel, but I can't remember if it also tracked ip address of the pixel request.  I'm asking because I want to create an alert when certain kinds of messages are being shared.  One way for us to do this is to note the time and geo of opens.  and if links we are sharing are being shared, simply turn them off or redirect.

**Comment by epipheus** [comment]
For example, the documentation shows click tracking events, but I don't see an open event with ip_addr

**Comment by willpower232** [comment]
It appears that the database does store the IP address for opens and clicks.

The webhook for clicks also includes the IP address so you should be able to monitor this from your application. As you mentioned, the open webhook doesn't seem to be documented but this was noticed in https://github.com/postalhq/postal/issues/629 and also should include the IP address.

In order to achieve your desired behaviour, each link in your email would have to redirect via your application to allow you to control it. Adding this functionality to Postal itself would likely require a lot of changes that would upset future updates.

FWIW I believe you may encounter problems with people using different devices and services to receive and open email as I'd imagine you will see a plural of IP addresses for the same recipient but the webhooks will allow you to collect the information at the very least before you take any drastic action.

**Comment by epipheus** [comment]
I know I've said this before, but I really appreciate the high quality product you've built.  Thank you for all the work you've put in and your responsiveness.  Closing this out.
