### ISSUE TITLE
Letsencrypt ACMEv1

### ISSUE THREAD

**Issue by iammattmartin** [postalhq/postal#970]
We've had a warning from LE about ACMEv1 from our postal install.

```
According to our records, the software client you're using to get Let's 
Encrypt TLS/SSL certificates issued or renewed at least one HTTPS certificate 
in the past two weeks using the ACMEv1 protocol. Your client's IP address was:

x.x.x.x

Beginning June 1, 2020, we will stop allowing new domains to validate using 
the ACMEv1 protocol. You should upgrade to an ACMEv2 compatible client before 
then, or certificate issuance will fail. For most people, simply upgrading to 
the latest version of your existing client will suffice. You can view the 
client list at: https://letsencrypt.org/docs/client-options/
```

We're not sure if this has been addressed yet or maybe something that needs to be?

**Comment by willpower232** [comment]
As you can see from [lib/postal/lets_encrypt.rb](https://github.com/postalhq/postal/blob/1ef7dbd67ee3476517ed98297050872f02deec3b/lib/postal/lets_encrypt.rb), the endpoints have already been updated in the source code and I've checked the release file to confirm its in there too so make sure you have updated your Postal to the latest version.

If you can't update your Postal because you've made changes, you would have to incorporate the changes from the commit: https://github.com/postalhq/postal/commit/1ef7dbd67ee3476517ed98297050872f02deec3b

If you use Lets Encrypt on the server to provide the certificate for nginx, you should make sure that client is up to date as well.

**Comment by iammattmartin** [comment]
Ta, more of a precautionary check as not upgraded for a while due to some changes made and that #296 needs manually adding.

That could do with a proper merge in as I suspect would help overall.

**Comment by willpower232** [comment]
Haha yeah, we're in a similar spot. I'll be doing a diff of the current and latest code on the server to see what the differences are next week.

On the other hand, hopefully atech will get a chance to do some updates before June so you have a bit of time and a probable chance to do a bigger update later if you wish.
