### ISSUE TITLE
wildcard subdomains

### ISSUE THREAD

**Issue by SHELA** [postalhq/postal#986]
i want route all emails that from *.@*.domain.com
MX record created to *.domain.com
but in Postal no way to create such route HTTP *.domain.com
so, what to do?
Thank You

**Comment by willpower232** [comment]
Unfortunately that is correct, the current model is that you need to be able to add the specific domain to Postal in order to send and receive messages for it.

If you aren't going to be able to know and set up each subdomain within Postal, you may want to use a more catch-all email address from a more traditional email system.
